### ISSUE TITLE
Problems running samples

### ISSUE THREAD

**Issue by ngunsu** [uuudown/SBNN#1]
For some reason, I have only successfully run mnist_mlp. When running other models, the output is always the same. For example, when running cifar_vgg the output is

/============================
Inference_Time: 0.002 ms.
 /============================
/======Label======
3 8 8 0 6 6 1 6 3 1 0 9 5 7 9 8 5 7 8 6 7 0 4 9 5 2 4 0 9 6 6 5 4 5 9 2 4 1 9 5 4 6 5 6 0 9 3 9 7 6 9 8 0 3 8 8 7 7 4 6 7 3 6 3 6 2 1 2 3 7 2 6 8 8 0 2 9 3 3 8 8 1 1 7 2 5 2 7 8 9 0 3 8 6 4 6 6 0 0 7 4 5
6 3 1 1 3 6 8 7 4 0 6 2 1 3 0 4 2 7 8 3 1 2 8 0 8 3
/=====Predict=======
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
/=====Batch Accuracy:128=======
Top-1:10.156250%
Top-5:10.156250%

I am using a RTX2080 TI, CUDA 10.0, and sm_75. The only changes to the code were setting dev to 0 and the file path of the image dataset.

**Comment by uuudown** [comment]
Thanks for your questions. This was tested on Volta V100 and Pascal P100. I
recently also test it on RTX2080Ti and met this issue. The reason is start
from Turing, they change the way of configuring of the shared memory.
Should be fine if you use the following two lines instead:
int shared_memory = 512*sizeof(int)*32;
cudaFuncSetAttribute(vggnet64, cudaFuncAttributeMaxDynamicSharedMemorySize,
shared_memory);

Best Regards,
Ang.

**Comment by ngunsu** [comment]
Many thanks, that solved the issue

**Comment by Courtesy-Xs** [comment]
Sorry to bother，Is this problem solved？I‘ve done that as you said，but the result of cifar_vgg still seems wrong，as following：

============================
Inference_Time: 8.075 ms.
============================
======Label======
3 8 8 0 6 6 1 6 3 1 0 9 5 7 9 8 5 7 8 6 7 0 4 9 5 2 4 0 9 6 6 5 4 5 9 2 4 1 9 5 4 6 5 6 0 9 3 9 7 6 9 8 0 3 8 8 7 7 4 6 7 3 6 3 
=====Predict=======
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
=====Batch Accuracy:64=======
Top-1:4.687500%
Top-5:46.875000%

I am using a Tesla T4, CUDA 11.1, and sm_75. The only changes to the code were setting dev to 0 and the file path of the image dataset.
